version: "3.7"

services:
  db:
    image: postgres
    container_name: rentalx_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rentalx_admin
      - POSTGRES_PASSWORD=rentalx_admin
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
    #network_mode: host

  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    #network_mode: host
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
